python3 ../../code/download_data.py 
python3 ../../code/expected_updates.py 
python3 ../../code/generate_list_of_peers.py 
python3 ../../code/generate_asn_vp_ip_mapping.py
python3 ../../code/generate_missed_received_lists.py
python3 ../../code/label_paths.py 
python3 ../../code/graph_from_as_paths.py 
python3 ../../code/heuristics_pinpointing.py
python3 ../../code/path_format_BeCAUSe.py
python3 ../../code/MCMC_network_tomography.py
python3 ../../code/HMC_network_tomography.py
python3 ../../code/create_summaries.py
